version: '3.5'

services:
  vote-system:
    # Change "main" to use a specific version.
    # You can see all tags at https://github.com/users/WesleyKlop/packages/container/vote-system/versions
    image: ghcr.io/wesleyklop/vote-system:main
    # build: .
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost']
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./storage/app:/app/storage/app
      - ./storage/logs:/app/storage/logs
      - ./.env:/app/.env
    networks:
      - net
    ports:
      - '8080:80'
    depends_on:
      - postgres
    restart: on-failure
  postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - net
    expose:
      - 5432
    restart: on-failure

networks:
  net:

volumes:
  db-data:
