name: Deliver

on:
    push:
        branches:
            - master
    release:
        types: [created]
    schedule:
        - cron: '0 4 * * 0' # Weekly on Sundays at 02:00
    pull_request:

env:
    IMAGE_NAME: w3ssl3y/vote-system

jobs:
    deliver:
        name: Build & Push Docker image
        runs-on: ubuntu-latest
        outputs:
            image: ${{ env.IMAGE_NAME }}:${{ steps.publish.outputs.tag }}
        steps:
            - uses: actions/checkout@v2
            - id: publish
              uses: elgohr/Publish-Docker-Github-Action@master
              with:
                  name: ${{ env.IMAGE_NAME }}
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}
                  tag_semver: true
                  cache: ${{ github.event_name != 'schedule' }}
