name: Deliver

on:
  push:
    branches:
      - main
  release:
    types:
      - created
  schedule:
    - cron: '0 4 * * 0' # Weekly on Sundays at 02:00

env:
  IMAGE_NAME: wesleyklop/vote-system

jobs:
  deliver:
    name: Build & Push Docker image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          pull: ${{ github.event_name != 'schedule' }}
          push: true
          cache-from: ${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline
          tags: latest
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
