name: Deliver

on:
  push:
    branches:
      - main
  release:
    types:
      - created
  schedule:
    - cron: '0 4 * * 0' # Weekly on Sundays at 02:00

env:
  IMAGE_NAME: WesleyKlop/vote-system

jobs:
  deliver:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
          registry: ghcr.io
          repository: ${{ env.IMAGE_NAME }}
          tag_with_ref: true
          add_git_labels: true
